apiVersion: eventrouter.krateo.io/v1alpha1
kind: Registration
metadata:
  name: event-service-registration
spec:
  endpoint: http://event-service.{{ .Release.Namespace }}.svc
  serviceName: event-service
