{{- if .Values.openshift }}
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-helm-controllerconfig
spec:
  securityContext: {}
  podSecurityContext: {}
---
{{- end }}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.15.0
  packagePullPolicy: IfNotPresent
  {{- if .Values.openshift }}
  controllerConfigRef:
    name: provider-helm-controllerconfig
  {{- end }}
